trigger: none

pool:
  vmImage: "ubuntu-latest"

variables:
  par_Base_Name: "Test"
  par_Environment_Prefix: "T"
  par_Location_Name: "westeurope"
  par_Location_Prefix: "WEu"
  par_Service_Connection_Name: "TEST-Connection"
  par_SubscriptionID:
  par_Template_File: "./core-main.bicep"
  # par_Parameters_File: "./parameters/staging.bicepparam"

parameters:
  - name: deployTest
    type: boolean
    default: false

stages:
  - stage: Lint
    jobs:
      - job: Lint_Code
        steps:
          - script: |
              az bicep build --file $(par_Template_File)
            name: LintBicepCode
            displayName: Run Bicep linter

  - stage: Validate
    jobs:
      - job: Validate_Bicep_Code
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            name: PreflightValidation
            displayName: Preflight Validation
            inputs:
              connectedServiceName: $(par_Service_Connection_Name)
              deploymentScope: Subscription
              subscriptionId: $(par_SubscriptionID)
              location: $(par_Location_Name)
              deploymentMode: Validation
              csmFile: $(par_Template_File)
              deploymentName: "$(par_Environment_Prefix)-$(par_Location_Prefix)-$(par_Base_Name)"
              overrideParameters: "-par_Environment_Prefix $(par_Environment_Prefix) -par_Base_Name $(par_Base_Name) -par_Location_Prefix $(par_Location_Prefix)"

  - stage: Preview
    jobs:
      - job: Preview
        steps:
          - task: AzureCLI@2
            name: RunWhatIf
            displayName: Run what-if
            inputs:
              azureSubscription: $(par_Service_Connection_Name)
              deploymentScope: Subscription
              subscriptionId: $(par_SubscriptionID)
              location: $(par_Location_Name)
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                az deployment sub what-if \
                  --location westeurope \
                  --template-file $(par_Template_File)

  - stage: Deploy
    jobs:
      - job: Deploy
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            name: Deploy
            displayName: Deploy to Azure
            inputs:
              connectedServiceName: $(par_Service_Connection_Name)
              deploymentScope: Subscription
              subscriptionId: $(par_SubscriptionID)
              location: $(par_Location_Name)
              deploymentMode: Incremental
              csmFile: $(par_Template_File)
              deploymentName: "$(par_Environment_Prefix)-$(par_Location_Prefix)-$(par_Base_Name)"
              overrideParameters: "-par_Environment_Prefix $(par_Environment_Prefix) -par_Base_Name $(par_Base_Name) -par_Location_Prefix $(par_Location_Prefix)"
