trigger: none

pool:
  vmImage: "ubuntu-latest"

variables:
  parBaseName: "Test"
  parEnvironment_Prefix: "T"
  parLocation_Name: "westeurope"
  parLocation_Prefix: "WEu"
  parService_Connection_Name: "TEST-Connection"
  parSubscriptionID:
  parTemplateFile: "./core-main.bicep"
  # par_Parameters_File: "./parameters/staging.bicepparam"

parameters:
  - name: deployTest
    type: boolean
    default: false

stages:
  - stage: Lint
    jobs:
      - job: Lint_Code
        steps:
          - script: |
              az bicep build --file $(parTemplateFile)
            name: LintBicepCode
            displayName: Run Bicep linter

  - stage: Validate
    jobs:
      - job: Validate_Bicep_Code
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            name: PreflightValidation
            displayName: Preflight Validation
            inputs:
              connectedServiceName: $(parServiceConnectionName)
              deploymentScope: Subscription
              subscriptionId: $(parSubscriptionID)
              location: $(parLocationName)
              deploymentMode: Validation
              csmFile: $(parTemplateFile)
              deploymentName: "$(parEnvironmentPrefix)-$(parLocationPrefix)-$(parBaseName)"
              overrideParameters: "-parEnvironmentPrefix $(parEnvironmentPrefix) -parBaseName $(parBaseName) -parLocationPrefix $(parLocationPrefix)"

  - stage: Preview
    jobs:
      - job: Preview
        steps:
          - task: AzureCLI@2
            name: RunWhatIf
            displayName: Run what-if
            inputs:
              azureSubscription: $(parServiceConnectionName)
              deploymentScope: Subscription
              subscriptionId: $(parSubscriptionID)
              location: $(parLocationName)
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                az deployment sub what-if \
                  --location westeurope \
                  --template-file $(parTemplateFile)

  - stage: Deploy
    jobs:
      - job: Deploy
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            name: Deploy
            displayName: Deploy to Azure
            inputs:
              connectedServiceName: $(parServiceConnectionName)
              deploymentScope: Subscription
              subscriptionId: $(parSubscriptionID)
              location: $(parLocationName)
              deploymentMode: Incremental
              csmFile: $(parTemplateFile)
              deploymentName: "$(parEnvironmentPrefix)-$(parLocationPrefix)-$(parBaseName)"
              overrideParameters: "-parEnvironmentPrefix $(parEnvironmentPrefix) -parBaseName $(parBaseName) -parLocationPrefix $(parLocationPrefix)"
