name: Core_Main_Deployment
on: [workflow_dispatch]

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - 'deploy/**'

permissions:
  id-token: write
  contents: read

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Bicep Linter
      run: az bicep build --file deploy/main.bicep

  Validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      name: Signing to Azure
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - uses: azure/arm-deploy@v1
      name: Preflight validation
      with:
        deploymentName: Core-Main-Deployment #${{ github.run_number }}
        scope: Subscription
        region: Northeurope
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        template: ./core-main.bicep
        deploymentMode: Validate
        # parameters:
        #   # aksCluster_SshPublicKey=${{ secrets.AKS_SSH_KEY }}

  Build:
    runs-on: ubuntu-latest
    needs: [Lint, Validate]
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      name: Signing to Azure
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - uses: azure/arm-deploy@v1
      name: Deployment
      with:
        deploymentName: Core-Main-Deployment #${{ github.run_number }}
        scope: Subscription
        region: Northeurope
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        template: ./core-main.bicep
        failonStdErr: false
        # parameters:
        #   # aksCluster_SshPublicKey=${{ secrets.AKS_SSH_KEY }}